### ISSUE TITLE
Blinking middle Dots

### ISSUE THREAD

**Issue by carl1961** [leonvandenbeukel/7-Segment-Digital-Clock-V2#6]
Awesome! Clock @leonvandenbeukel
Any one have a clue where I can fine the code or a way to stop the blinking 2 dots? I looked every where in 7-Segment-WiFi-Clock.ino,  I have a hunch it may be somewhere in the FastLED lib files? Thanks for any advice

**Comment by helpquick** [comment]
just comment out the ``displayDots`` on line 326 (in 7-Segment-Digital-Clock-V2/7-Segment-Clock/7-Segment-Clock.ino)

**Comment by carl1961** [comment]
> just comment out the `displayDots` on line 326 (in 7-Segment-Digital-Clock-V2/7-Segment-Clock/7-Segment-Clock.ino)

Thanks for the Fast post, Just tried that, Thanks, but it turns the dots off, I was trying to just stop the blinking.  I tried your code too, Great code by the way.

**Comment by helpquick** [comment]
@carl1961 
Ah, ok, replace the `displyDots` function (around line 403) with:

```
void displayDots(CRGB color) {
    LEDs[42] = color;
    LEDs[43] = color;
}
```

That'll for force the dots always on.

**Comment by carl1961** [comment]
> @carl1961
> Ah, ok, replace the `displyDots` function (around line 403) with:
> 
> ```
> void displayDots(CRGB color) {
>     LEDs[42] = color;
>     LEDs[43] = color;
> }
> ```
> 
> That'll for force the dots always on.

Thanks @helpquick That worked Thanks! your true to your Name!
